services:
  db:
    image: postgres:12
    restart: always
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env

  bot:
    build:
      context: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    command: [ "python", "bot.py" ]

volumes:
  app-db-data:
    external: true